site_name: Мой сайт
site_author: Виктория Андриянова
site_description: Минимальная кастомная тема

theme:
  name: mkdocs
  custom_dir: overrides/

nav:
  - Главная: index.md
  - Отчёт по 1 лабораторной: report_1.md
  - Отчёт по 2 лабораторной: report_2.md


extra_css:
  - assets/css/custom.min.css